# Generated by Django 5.0.7 on 2024-08-09 01:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_time', models.DurationField()),
                ('records_inserted', models.IntegerField()),
                ('records_failed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GenomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.IntegerField()),
                ('tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genres', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbId', models.CharField(max_length=255)),
                ('tmdbId', models.CharField(max_length=255)),
                ('movieId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movielens_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='GenomeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagId', models.IntegerField()),
                ('relevance', models.FloatField()),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('rating', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('tag', models.CharField(max_length=255)),
                ('timestamp', models.BigIntegerField()),
                ('movieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens_app.movie')),
            ],
        ),
    ]
