# Generated by Django 5.0.7 on 2024-08-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielens_app', '0002_fileupload_delete_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='processing_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='records_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='records_inserted',
            field=models.IntegerField(default=0),
        ),
    ]
