# Generated by Django 5.0.7 on 2024-08-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielens_app', '0002_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='processing_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='records_failed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='records_inserted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
