# Generated by Django 5.0.7 on 2024-08-07 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielens_app', '0003_remove_movie_id_alter_movie_movieid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genomescore',
            name='movieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens_app.movie'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens_app.movie'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='movieId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielens_app.movie'),
        ),
    ]
